name: Python package

# instantiate github workflow on commit
on: [push]

jobs:
  build:
    # use an ubuntu based VM to install python 3.8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f ../../server/requirements.txt ]; then pip install -r ../../server/requirements.txt; fi
      - name: Test with python script
        run: |
          python ../../server/tests/tests.py
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with: 
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}